# Generated by Django 4.1.1 on 2022-10-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankingType",
            fields=[
                (
                    "auto_increment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="BankingMethod",
            fields=[
                (
                    "auto_increment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
                ("logo", models.ImageField(upload_to="logos")),
                (
                    "types",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="banking.bankingtype",
                    ),
                ),
            ],
        ),
    ]
