# Generated by Django 4.1.2 on 2022-11-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newuser",
            old_name="client_identity_id",
            new_name="id",
        ),
    ]
